### ISSUE TITLE
linux运行报错: System.DllNotFoundException

### ISSUE THREAD

**Issue by cuiliang** [sdcb/PaddleSharp#2]
```dotnet run
Unhandled exception. System.DllNotFoundException: Unable to load shared library 'paddle_inference_c' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libpaddle_inference_c: cannot open shared object file: No such file or directory
   at Sdcb.PaddleInference.Native.PaddleNative.PD_ConfigCreate()
   at Sdcb.PaddleInference.PaddleConfig..ctor()
   at Sdcb.PaddleOCR.PaddleOcrDetector..ctor(String modelDir)
   at Sdcb.PaddleOCR.PaddleOcrAll..ctor(String modelPath, String labelFilePath)
   at LocalPaddleOcr.Program.Main(String[] args) in /home/cuiliang/dotnetocr/Program.cs:line 30
   at LocalPaddleOcr.Program.<Main>(String[] args)
```

**Comment by sdcb** [comment]
Directly deploy in Linux environment requires compiled OpenCvSharp4 native library and paddlepaddle inference C library(and all it's dependencies).
