### ISSUE TITLE
System.AccessViolationException 异常

### ISSUE THREAD

**Issue by cuiliang** [sdcb/PaddleSharp#45]
在WIndows 2019 IIS中运行，偶发性。 .Net 6和.Net 7都会发生。

```
Application: w3wp.exe
CoreCLR Version: 7.0.523.17405
.NET Version: 7.0.5
Description: The process was terminated due to an unhandled exception.
Exception Info: System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
Stack:
   at Sdcb.PaddleInference.Native.PaddleNative.PD_PredictorRun(IntPtr)
   at Sdcb.PaddleInference.Native.PaddleNative.PD_PredictorRun(IntPtr)
   at Sdcb.PaddleOCR.PaddleOcrClassifier.ShouldRotate180(OpenCvSharp.Mat)
   at Sdcb.PaddleOCR.PaddleOcrClassifier.Run(OpenCvSharp.Mat)
   at Sdcb.PaddleOCR.PaddleOcrAll+<>c__DisplayClass24_0.<Run>b__0(OpenCvSharp.RotatedRect)
   at System.Linq.Enumerable+SelectArrayIterator`2[[OpenCvSharp.RotatedRect, OpenCvSharp, Version=1.0.0.0, Culture=neutral, PublicKeyToken=6adad1e807fea099],[System.__Canon, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].ToArray()
   at Sdcb.PaddleOCR.PaddleOcrAll.Run(OpenCvSharp.Mat, Int32)
   at Sdcb.PaddleOCR.QueuedPaddleOcrAll.ProcessQueue()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(System.Threading.Thread, System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task ByRef, System.Threading.Thread)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool+WorkerThread.WorkerThreadStart()
```

**Comment by n0099** [comment]
ubuntu2204下使用2.4.2 mkldnn的paddleinfer长期运行从未遇到过

**Comment by cuiliang** [comment]
关闭180度检测可以避免这个现象出现

**Comment by n0099** [comment]
我一直开着`Enable180Classification`啊
https://github.com/n0099/TiebaMonitor/blob/3fe39b0c4d9ea9336aa2187a650752a8872dca6d/c%23/imagePipeline/src/Ocr/PaddleOcrRecognizerAndDetector.cs#L34

**Comment by cuiliang** [comment]
有可能你还没有遇到会产生这个问题的图片。 我之前是开了一个服务，并发请求比较多的时候偶尔出现的，而且图片是用户上传的，各种图都有。 @n0099

**Comment by n0099** [comment]
我已经ocr了200k+张了，您遇到的能稳定复现的图片是什么样的，能上传一份吗

**Comment by cuiliang** [comment]
@n0099 没有能稳定复现，而且也没有图片，图片是用户使用服务的时候上传的，base64直接识别的，也没有保存。

**Comment by n0099** [comment]
那阁下用的是mkldnn吗

> 并发请求比较多

您是多线程并行调用同一个类实例上的`PaddleOcrAll.Run()`的吗，我记得使用CUDA时paddleinfer是线程不安全的，https://github.com/PaddlePaddle/Paddle/issues?q=is%3Aissue+%E5%A4%9A%E7%BA%BF%E7%A8%8B

**Comment by cuiliang** [comment]
> 那阁下用的是mkldnn吗
> 
> > 并发请求比较多
> 
> 您是多线程并行调用同一个类实例上的`PaddleOcrAll.Run()`的吗，我记得使用CUDA时paddleinfer是线程不安全的，https://github.com/PaddlePaddle/Paddle/issues?q=is%3Aissue+%E5%A4%9A%E7%BA%BF%E7%A8%8B

是的。 后来我都关掉了180和方向检测跑了。

**Comment by n0099** [comment]
我没有多线程并行调用同一个`.Run()`

**Comment by RockNHawk** [comment]
我处理的图片数量可能有上万张。
我找一下相关图片传上来。

**Comment by sdcb** [comment]
Please refer to [this example](https://github.com/sdcb/PaddleSharp/blob/master/docs/ocr.md#how-to-integrate-sdcbpaddleocr-to-aspnet-core) to use.
