### ISSUE TITLE
System.AccessViolationException

### ISSUE THREAD

**Issue by SteveArias** [sdcb/PaddleSharp#47]
I get the following error when trying to run code similar to the [Quick Start](https://github.com/sdcb/PaddleSharp/blob/master/docs/ocr.md#windowslocal-model-detection-and-recognitionall)

Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
Repeat 2 times:
--------------------------------
   at Sdcb.PaddleInference.Native.PaddleNative.PD_PredictorRun(IntPtr)
--------------------------------
   at Sdcb.PaddleOCR.PaddleOcrDetector.Run(OpenCvSharp.Mat)
   at Sdcb.PaddleOCR.PaddleOcrAll.Run(OpenCvSharp.Mat, Int32)
   at ImageLibrary.Clients.Getty.GettyImageClient.PopulateResultsV2(System.Object, SegmentType, ImageLibrary.DataSchemas.HeroImage.ImageSearchRequest)
   at ImageLibrary.Clients.Getty.GettyImageClient.GetEditorialImagesExecute(Segment, ImageLibrary.DataSchemas.HeroImage.ImageSearchRequest, System.Collections.Generic.IList`1<ImageFilterOptions>, ImageSortOption, SegmentType)
   at ImageLibrary.Clients.Getty.GettyImageClient.GetEditorialImages(Segment, ImageLibrary.DataSchemas.HeroImage.ImageSearchRequest, System.Collections.Generic.IList`1<ImageFilterOptions>, ImageSortOption, SegmentType)
   at ImageLibrary.ImageScrapper.NonPeopleImageScrapper.SearchEditorialImages(System.Collections.Generic.List`1<ImageLibrary.DataSchemas.HeroImage.ImageSearchResult>, ImageLibrary.DataSchemas.HeroImage.ImageSearchRequest, Int32, System.Collections.Generic.List`1<System.String>, SegmentType, Int32 ByRef)
   at ImageLibrary.ImageScrapper.NonPeopleImageScrapper.GetTopImages(ImageLibrary.DataSchemas.HeroImage.ImageSearchRequest, Int32, ImageSortOption, SegmentType, Boolean)
   at ImageScrapper.Program+<>c__DisplayClass7_9.<ExecuteScraperProcess>b__0(System.String)
   at System.Threading.Tasks.Parallel+<>c__DisplayClass33_0`2[[System.__Canon, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].<ForEachWorker>b__0(Int32)
   at System.Threading.Tasks.Parallel+<>c__DisplayClass19_0`1[[System.__Canon, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].<ForWorker>b__1(System.Threading.Tasks.RangeWorker ByRef, Int32, Boolean ByRef)
   at System.Threading.Tasks.TaskReplicator+Replica.Execute()
   at System.Threading.Tasks.TaskReplicator+Replica+<>c.<Execute>b__7_0(System.Object)
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task+<>c.<.cctor>b__272_0(System.Object)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(System.Threading.Thread, System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task ByRef, System.Threading.Thread)
   at System.Threading.Tasks.Task.ExecuteEntryUnsafe(System.Threading.Thread)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool+WorkerThread.WorkerThreadStart()
   at System.Threading.Thread.StartCallback()
   
   What steps can I now take to get to the cause of the problem?

**Comment by sdcb** [comment]
If you running on multi-threading environment(like will run OCR in different threads), I suggest you using singleton `QueuedPaddleOcrAll`, usage here: https://github.com/sdcb/PaddleSharp/blob/master/docs/ocr.md#how-to-integrate-sdcbpaddleocr-to-aspnet-core

ASP.NET Core Example here: https://github.com/sdcb/paddlesharp-ocr-aspnetcore-demo

Please tell me if you have any further question.

**Comment by sdcb** [comment]
Please refer to [this example](https://github.com/sdcb/PaddleSharp/blob/master/docs/ocr.md#how-to-integrate-sdcbpaddleocr-to-aspnet-core) to use.
