### ISSUE TITLE
External component has thrown an exception (Windows Server 2019)

### ISSUE THREAD

**Issue by ytchen2833** [sdcb/PaddleSharp#70]
It can run on Windows 10, but throw an exception on the windows server IIS. The error log is shown as below.

**ErrorLog**
```
2023-11-13 09:20:11,821 [ERROR] [(null)] [8] [IISHttpServer] [?] Connection ID "17582052951160001624", Request ID "8000145b-0001-f400-b63f-84710c7967bb": An unhandled exception was thrown by the application.
System.Runtime.InteropServices.SEHException (0x80004005): External component has thrown an exception.
   at Sdcb.PaddleInference.Native.PaddleNative.PD_PredictorRun(IntPtr pd_predictor)
   at Sdcb.PaddleInference.PaddlePredictor.Run()
   at Sdcb.PaddleOCR.PaddleOcrDetector.RunRaw(Mat src, Size& resizedSize)
   at Sdcb.PaddleOCR.PaddleOcrDetector.Run(Mat src)
   at Sdcb.PaddleOCR.PaddleOcrAll.Run(Mat src, Int32 recognizeBatchSize)
   at Sdcb.PaddleOCR.QueuedPaddleOcrAll.ProcessQueue()
```

I turned stdoutLogEnabled on, and the error log is shown as below.
```
fail: Microsoft.AspNetCore.Server.IIS.Core.IISHttpServer[2]
      Connection ID "17870283331606688933", Request ID "800034a6-0002-f800-b63f-84710c7967bb": An unhandled exception was thrown by the application.
      System.Runtime.InteropServices.SEHException (0x80004005): External component has thrown an exception.
         at Sdcb.PaddleInference.Native.PaddleNative.PD_PredictorRun(IntPtr pd_predictor)
         at Sdcb.PaddleInference.PaddlePredictor.Run()
         at Sdcb.PaddleOCR.PaddleOcrDetector.RunRaw(Mat src, Size& resizedSize)
         at Sdcb.PaddleOCR.PaddleOcrDetector.Run(Mat src)
         at Sdcb.PaddleOCR.PaddleOcrAll.Run(Mat src, Int32 recognizeBatchSize)
         at Sdcb.PaddleOCR.QueuedPaddleOcrAll.ProcessQueue()
```

**Environment**
Windows Server 2019 Standard
IIS 10.0.17763.1
.NET 6 Web API
<PackageReference Include="Sdcb.PaddleInference" Version="2.5.0.1" />
<PackageReference Include="Sdcb.PaddleInference.runtime.win64.mkl" Version="2.5.1" />
<PackageReference Include="Sdcb.PaddleOCR" Version="2.7.0" />
<PackageReference Include="Sdcb.PaddleOCR.Models.Local" Version="2.7.0" />

**Comment by sdcb** [comment]
Can you try my another project OpenVINO.NET: https://github.com/sdcb/OpenVINO.NET
Also provided PaddleOCR inference but it's better.

**Comment by kobruleht** [comment]
Should all usages of PaddleSharp replaced with OpenVINO.NET  ?
