### ISSUE TITLE
升级最新版依赖包报错Unable to find an entry point named 'PD_ConfigEnableONNXRuntime' in DLL 'paddle_inference_c'.”

### ISSUE THREAD

**Issue by wangning08115** [sdcb/PaddleSharp#99]
### Describe the bug

以前是老包使用正常，GPU的。
升级最新版依赖包报错Unable to find an entry point named 'PD_ConfigEnableONNXRuntime' in DLL 'paddle_inference_c'.”

System.EntryPointNotFoundException:“Unable to find an entry point named 'PD_ConfigEnableONNXRuntime' in DLL 'paddle_inference_c'.”

### Steps to reproduce the bug

升级最新版依赖包

**Comment by n0099** [comment]
去下个[`paddle_inference_c.so`](https://paddleinference.paddlepaddle.org.cn/v2.2/user_guides/download_lib.html#id1)把url path开头的`2.3.2`改成最新的`2.6.0`

**Comment by wangning08115** [comment]
@n0099   谢谢
我是windows，  【把url path开头的2.3.2】 这句啥意思， 我新手 没见过这个版本号？

**Comment by wangning08115** [comment]
@n0099 感谢，我卸载了nuget，安装了一个新包 Sdcb.PaddleInference.runtime.win64.cuda118_cudnn86_tr85_sm86_89  可以了。
但是遇到一个新问题：如下，windows 11

[Paddle2ONNX] Use opset_version = 11 for ONNX export.
[Paddle2ONNX] PaddlePaddle model is exported as ONNX format now.
[Paddle2ONNX] Use opset_version = 11 for ONNX export.
[Paddle2ONNX] PaddlePaddle model is exported as ONNX format now.
[Paddle2ONNX] Use opset_version = 11 for ONNX export.
[Paddle2ONNX] PaddlePaddle model is exported as ONNX format now.
[Paddle2ONNX] Use opset_version = 11 for ONNX export.
[Paddle2ONNX] PaddlePaddle model is exported as ONNX format now.
System.MethodAccessException: Attempt by method 'Sdcb.PaddleOCR.PaddleOcrDetector.RunRaw(OpenCvSharp.Mat, OpenCvSharp.Size ByRef)' to access method 'OpenCvSharp.Mat..ctor(Int32, Int32, OpenCvSharp.MatType, System.Array, Int64)' failed.
   at Sdcb.PaddleOCR.PaddleOcrDetector.RunRaw(Mat src, Size& resizedSize)
   at Sdcb.PaddleOCR.PaddleOcrDetector.Run(Mat src)
   at Sdcb.PaddleOCR.PaddleOcrAll.Run(Mat src, Int32 recognizeBatchSize)
   at Program.<Main>$(String[] args) in E:\Work\Company\StartPointOcrEngine\StartPointOcrEngine\StartPointOcrEngine.TestGPU\Program.cs:line 57

**Comment by wangning08115** [comment]
我搞好了：
OpenCvSharp 不能用最新版本。最新版本有bug， 我回退一个版本就可以运行了

**Comment by n0099** [comment]
https://github.com/sdcb/PaddleSharp/pull/78

**Comment by sdcb** [comment]
试一下最新的 Sdcb.PaddleOCR 2.7.0.3 版本，适配了最新的 OpenCvSharp
